version = 5.1.0
archive_dir = /etc/letsencrypt/archive/api.g52-genspa.xyz
cert = /etc/letsencrypt/live/api.g52-genspa.xyz/cert.pem
privkey = /etc/letsencrypt/live/api.g52-genspa.xyz/privkey.pem
chain = /etc/letsencrypt/live/api.g52-genspa.xyz/chain.pem
fullchain = /etc/letsencrypt/live/api.g52-genspa.xyz/fullchain.pem
[renewalparams]
account = 64d449d976fc845a3fd97f71a8d03888
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
api.g52-genspa.xyz = /var/www/certbot
