server {
    listen 443 ssl;
    server_name api.g52-genspa.xyz;

    ssl_certificate /etc/letsencrypt/live/api.g52-genspa.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.g52-genspa.xyz/privkey.pem;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
